IDIR =../include
CC=g++
CFLAGS=-O3 -std=c++11 -funroll-loops -m64 -march=native
ODIR=obj
LDIR =../lib

SRC = 

all: $(SRC)
	g++ $(CFLAGS) Main.cpp Eventlist.cpp Events.cpp Events_action.cpp Events_add.cpp Events_del.cpp Events_check.cpp Evolution.cpp Grid.cpp Input.cpp mtrand.cpp Results.cpp State.cpp -o gcc.exe
